name: ci
on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.0, 1.1.6]
          #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: make env - run poetry
        run: make env
      - name: Install coreutils for macOS
        if: matrix.os == 'macos-latest'
        run: brew install coreutils
      - name: make test
        run: make test
